name: Release

on:
  push:
    tags: v*.*.*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: make build

      - name: Archive
        run: make zip
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mc-bedrock-runner.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
